// -*- C++ -*-
#ifndef CMS3_H
#define CMS3_H
#include "Math/LorentzVector.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector>
#include <unistd.h>
typedef ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > LorentzVector;

// Generated with file: v1.0_leptontree/year_2017/DY_high.root

using namespace std;
class CMS3 {
private:
protected:
  unsigned int index;
  bool passes_SS_fo_looseMVA_noiso_v6_;
  TBranch *passes_SS_fo_looseMVA_noiso_v6_branch;
  bool passes_SS_fo_looseMVA_noiso_v6_isLoaded;
  float miniiso_;
  TBranch *miniiso_branch;
  bool miniiso_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *tag_p4_;
  TBranch *tag_p4_branch;
  bool tag_p4_isLoaded;
  int njets_;
  TBranch *njets_branch;
  bool njets_isLoaded;
  int HLT_Ele17_CaloIdM_TrackIdM_PFJet30_;
  TBranch *HLT_Ele17_CaloIdM_TrackIdM_PFJet30_branch;
  bool HLT_Ele17_CaloIdM_TrackIdM_PFJet30_isLoaded;
  int HLT_Mu8_TrkIsoVVL_;
  TBranch *HLT_Mu8_TrkIsoVVL_branch;
  bool HLT_Mu8_TrkIsoVVL_isLoaded;
  float evt_corrMET_;
  TBranch *evt_corrMET_branch;
  bool evt_corrMET_isLoaded;
  bool passes_SS_fo_v6_;
  TBranch *passes_SS_fo_v6_branch;
  bool passes_SS_fo_v6_isLoaded;
  int HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_;
  TBranch *HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_branch;
  bool HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_isLoaded;
  bool evt_isRealData_;
  TBranch *evt_isRealData_branch;
  bool evt_isRealData_isLoaded;
  int HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30_;
  TBranch *HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30_branch;
  bool HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30_isLoaded;
  float ip3d_;
  TBranch *ip3d_branch;
  bool ip3d_isLoaded;
  int HLT_Ele12_CaloIdM_TrackIdM_PFJet30_;
  TBranch *HLT_Ele12_CaloIdM_TrackIdM_PFJet30_branch;
  bool HLT_Ele12_CaloIdM_TrackIdM_PFJet30_isLoaded;
  float coneCorrPt_;
  TBranch *coneCorrPt_branch;
  bool coneCorrPt_isLoaded;
  int HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_;
  TBranch *HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_branch;
  bool HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_isLoaded;
  int id_;
  TBranch *id_branch;
  bool id_isLoaded;
  int HLT_Ele23_CaloIdM_TrackIdM_PFJet30_;
  TBranch *HLT_Ele23_CaloIdM_TrackIdM_PFJet30_branch;
  bool HLT_Ele23_CaloIdM_TrackIdM_PFJet30_isLoaded;
  int HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_;
  TBranch *HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_branch;
  bool HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_isLoaded;
  int HLT_Ele8_CaloIdM_TrackIdM_PFJet30_;
  TBranch *HLT_Ele8_CaloIdM_TrackIdM_PFJet30_branch;
  bool HLT_Ele8_CaloIdM_TrackIdM_PFJet30_isLoaded;
  int nloose_mu_;
  TBranch *nloose_mu_branch;
  bool nloose_mu_isLoaded;
  bool isTriggerSafenoIso_;
  TBranch *isTriggerSafenoIso_branch;
  bool isTriggerSafenoIso_isLoaded;
  bool passes_any_trigger_;
  TBranch *passes_any_trigger_branch;
  bool passes_any_trigger_isLoaded;
  int HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int evt_run_;
  TBranch *evt_run_branch;
  bool evt_run_isLoaded;
  bool passes_SS_tight_noiso_v6_;
  TBranch *passes_SS_tight_noiso_v6_branch;
  bool passes_SS_tight_noiso_v6_isLoaded;
  float ht_SS_;
  TBranch *ht_SS_branch;
  bool ht_SS_isLoaded;
  float puweight_;
  TBranch *puweight_branch;
  bool puweight_isLoaded;
  TString sample_;
  TBranch *sample_branch;
  bool sample_isLoaded;
  int HLT_DoubleMu8_Mass8_PFHT300_;
  TBranch *HLT_DoubleMu8_Mass8_PFHT300_branch;
  bool HLT_DoubleMu8_Mass8_PFHT300_isLoaded;
  float ptratio_v5_;
  TBranch *ptratio_v5_branch;
  bool ptratio_v5_isLoaded;
  int HLT_Mu17_TrkIsoVVL_;
  TBranch *HLT_Mu17_TrkIsoVVL_branch;
  bool HLT_Mu17_TrkIsoVVL_isLoaded;
  int HLT_Ele18_CaloIdM_TrackIdM_PFJet30_;
  TBranch *HLT_Ele18_CaloIdM_TrackIdM_PFJet30_branch;
  bool HLT_Ele18_CaloIdM_TrackIdM_PFJet30_isLoaded;
  int nvtx_;
  TBranch *nvtx_branch;
  bool nvtx_isLoaded;
  bool isTriggerSafe_;
  TBranch *isTriggerSafe_branch;
  bool isTriggerSafe_isLoaded;
  int HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int njets_recoil_;
  TBranch *njets_recoil_branch;
  bool njets_recoil_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *close_jet_v5_;
  TBranch *close_jet_v5_branch;
  bool close_jet_v5_isLoaded;
  int motherID_;
  TBranch *motherID_branch;
  bool motherID_isLoaded;
  int HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_;
  TBranch *HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_branch;
  bool HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30_isLoaded;
  float tag_pt_;
  TBranch *tag_pt_branch;
  bool tag_pt_isLoaded;
  bool passes_SS_fo_looseMVA_v6_;
  TBranch *passes_SS_fo_looseMVA_v6_branch;
  bool passes_SS_fo_looseMVA_v6_isLoaded;
  bool passes_SS_tight_v6_;
  TBranch *passes_SS_tight_v6_branch;
  bool passes_SS_tight_v6_isLoaded;
  bool have_tag_;
  TBranch *have_tag_branch;
  bool have_tag_isLoaded;
  int nFOs_SS_;
  TBranch *nFOs_SS_branch;
  bool nFOs_SS_isLoaded;
  int HLT_IsoMu27_;
  TBranch *HLT_IsoMu27_branch;
  bool HLT_IsoMu27_isLoaded;
  int ntight_el_;
  TBranch *ntight_el_branch;
  bool ntight_el_isLoaded;
  float ip3derr_;
  TBranch *ip3derr_branch;
  bool ip3derr_isLoaded;
  float ptrelv1_;
  TBranch *ptrelv1_branch;
  bool ptrelv1_isLoaded;
  int HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300_;
  TBranch *HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300_branch;
  bool HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300_isLoaded;
  int HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int evt_event_;
  TBranch *evt_event_branch;
  bool evt_event_isLoaded;
  int HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_;
  TBranch *HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_branch;
  bool HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_isLoaded;
  bool passes_met_filters_;
  TBranch *passes_met_filters_branch;
  bool passes_met_filters_isLoaded;
  float dilep_mass_;
  TBranch *dilep_mass_branch;
  bool dilep_mass_isLoaded;
  int nloose_el_;
  TBranch *nloose_el_branch;
  bool nloose_el_isLoaded;
  int HLT_Ele12_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Ele12_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Ele12_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30_;
  TBranch *HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30_branch;
  bool HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30_isLoaded;
  int HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300_;
  TBranch *HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300_branch;
  bool HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300_isLoaded;
  int idx_;
  TBranch *idx_branch;
  bool idx_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *p4_;
  TBranch *p4_branch;
  bool p4_isLoaded;
  float scale1fb_;
  TBranch *scale1fb_branch;
  bool scale1fb_isLoaded;
  int HLT_Mu8_;
  TBranch *HLT_Mu8_branch;
  bool HLT_Mu8_isLoaded;
  bool passes_SS_fo_noiso_v6_;
  TBranch *passes_SS_fo_noiso_v6_branch;
  bool passes_SS_fo_noiso_v6_isLoaded;
  float evt_corrMETPhi_;
  TBranch *evt_corrMETPhi_branch;
  bool evt_corrMETPhi_isLoaded;
  int ntight_mu_;
  TBranch *ntight_mu_branch;
  bool ntight_mu_isLoaded;
  int HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_;
  TBranch *HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_branch;
  bool HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_isLoaded;
  float mt_;
  TBranch *mt_branch;
  bool mt_isLoaded;
  int HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30_;
  TBranch *HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30_branch;
  bool HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30_isLoaded;
  int evt_lumiBlock_;
  TBranch *evt_lumiBlock_branch;
  bool evt_lumiBlock_isLoaded;
  ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > *dilep_p4_;
  TBranch *dilep_p4_branch;
  bool dilep_p4_isLoaded;
  float trueNumInt_;
  TBranch *trueNumInt_branch;
  bool trueNumInt_isLoaded;
  int HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_;
  TBranch *HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_branch;
  bool HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_isLoaded;
  int HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_;
  TBranch *HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_branch;
  bool HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_isLoaded;
  int HLT_Ele23_CaloIdL_TrackIdL_IsoVL_;
  TBranch *HLT_Ele23_CaloIdL_TrackIdL_IsoVL_branch;
  bool HLT_Ele23_CaloIdL_TrackIdL_IsoVL_isLoaded;
  int HLT_Mu17_;
  TBranch *HLT_Mu17_branch;
  bool HLT_Mu17_isLoaded;
public:
  void Init(TTree *tree);
  void GetEntry(unsigned int idx);
  void LoadAllBranches();
  const bool &passes_SS_fo_looseMVA_noiso_v6();
  const float &miniiso();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &tag_p4();
  const int &njets();
  const int &HLT_Ele17_CaloIdM_TrackIdM_PFJet30();
  const int &HLT_Mu8_TrkIsoVVL();
  const float &evt_corrMET();
  const bool &passes_SS_fo_v6();
  const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ();
  const bool &evt_isRealData();
  const int &HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const float &ip3d();
  const int &HLT_Ele12_CaloIdM_TrackIdM_PFJet30();
  const float &coneCorrPt();
  const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const int &id();
  const int &HLT_Ele23_CaloIdM_TrackIdM_PFJet30();
  const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL();
  const int &HLT_Ele8_CaloIdM_TrackIdM_PFJet30();
  const int &nloose_mu();
  const bool &isTriggerSafenoIso();
  const bool &passes_any_trigger();
  const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &evt_run();
  const bool &passes_SS_tight_noiso_v6();
  const float &ht_SS();
  const float &puweight();
  const TString &sample();
  const int &HLT_DoubleMu8_Mass8_PFHT300();
  const float &ptratio_v5();
  const int &HLT_Mu17_TrkIsoVVL();
  const int &HLT_Ele18_CaloIdM_TrackIdM_PFJet30();
  const int &nvtx();
  const bool &isTriggerSafe();
  const int &HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL();
  const int &njets_recoil();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &close_jet_v5();
  const int &motherID();
  const int &HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const float &tag_pt();
  const bool &passes_SS_fo_looseMVA_v6();
  const bool &passes_SS_tight_v6();
  const bool &have_tag();
  const int &nFOs_SS();
  const int &HLT_IsoMu27();
  const int &ntight_el();
  const float &ip3derr();
  const float &ptrelv1();
  const int &HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300();
  const int &HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &evt_event();
  const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const bool &passes_met_filters();
  const float &dilep_mass();
  const int &nloose_el();
  const int &HLT_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const int &HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300();
  const int &idx();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &p4();
  const float &scale1fb();
  const int &HLT_Mu8();
  const bool &passes_SS_fo_noiso_v6();
  const float &evt_corrMETPhi();
  const int &ntight_mu();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL();
  const float &mt();
  const int &HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const int &evt_lumiBlock();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &dilep_p4();
  const float &trueNumInt();
  const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ();
  const int &HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const int &HLT_Ele23_CaloIdL_TrackIdL_IsoVL();
  const int &HLT_Mu17();
  static void progress( int nEventsTotal, int nEventsChain );
};

#ifndef __CINT__
extern CMS3 cms3;
#endif

namespace tas {

  const bool &passes_SS_fo_looseMVA_noiso_v6();
  const float &miniiso();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &tag_p4();
  const int &njets();
  const int &HLT_Ele17_CaloIdM_TrackIdM_PFJet30();
  const int &HLT_Mu8_TrkIsoVVL();
  const float &evt_corrMET();
  const bool &passes_SS_fo_v6();
  const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ();
  const bool &evt_isRealData();
  const int &HLT_Ele18_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const float &ip3d();
  const int &HLT_Ele12_CaloIdM_TrackIdM_PFJet30();
  const float &coneCorrPt();
  const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const int &id();
  const int &HLT_Ele23_CaloIdM_TrackIdM_PFJet30();
  const int &HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL();
  const int &HLT_Ele8_CaloIdM_TrackIdM_PFJet30();
  const int &nloose_mu();
  const bool &isTriggerSafenoIso();
  const bool &passes_any_trigger();
  const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &evt_run();
  const bool &passes_SS_tight_noiso_v6();
  const float &ht_SS();
  const float &puweight();
  const TString &sample();
  const int &HLT_DoubleMu8_Mass8_PFHT300();
  const float &ptratio_v5();
  const int &HLT_Mu17_TrkIsoVVL();
  const int &HLT_Ele18_CaloIdM_TrackIdM_PFJet30();
  const int &nvtx();
  const bool &isTriggerSafe();
  const int &HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL();
  const int &njets_recoil();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &close_jet_v5();
  const int &motherID();
  const int &HLT_Ele23_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const float &tag_pt();
  const bool &passes_SS_fo_looseMVA_v6();
  const bool &passes_SS_tight_v6();
  const bool &have_tag();
  const int &nFOs_SS();
  const int &HLT_IsoMu27();
  const int &ntight_el();
  const float &ip3derr();
  const float &ptrelv1();
  const int &HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300();
  const int &HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &evt_event();
  const int &HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ();
  const bool &passes_met_filters();
  const float &dilep_mass();
  const int &nloose_el();
  const int &HLT_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &HLT_Ele8_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const int &HLT_DoubleEle8_CaloIdM_TrackIdM_Mass8_PFHT300();
  const int &idx();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &p4();
  const float &scale1fb();
  const int &HLT_Mu8();
  const bool &passes_SS_fo_noiso_v6();
  const float &evt_corrMETPhi();
  const int &ntight_mu();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL();
  const float &mt();
  const int &HLT_Ele17_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const int &evt_lumiBlock();
  const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &dilep_p4();
  const float &trueNumInt();
  const int &HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL();
  const int &HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ();
  const int &HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30();
  const int &HLT_Ele23_CaloIdL_TrackIdL_IsoVL();
  const int &HLT_Mu17();
}
#endif
